purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6089471976738423
  brandStrength: 1
  lightness: 0.8733551157638431
  brandColors:
    - '#FFFFFF'
    - '#737D74'
    - '#0C1D0E'
    - '#AAB0AA'
    - '#3A483C'
  rhythmicContrast: 0.293159076012671
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Provident Consulting
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1525187
layout_spectrum: 0
