name: Provident Consulting
favicon: null
layout_spectrum: 0.16800177213735878
typography_spectrum: 0.08731290721334517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#045391'
    - '#172918'
    - '#649b43'
    - '#000000'
    - '#008000'
  brandStrength: 0.5
  lightness: 0.8733551157638431
  saturation: 0.6089471976738423
  rhythmicContrast: 0.293159076012671
purpose: []
