name: Provident Consulting
favicon: null
layout_spectrum: 0.16800177213735878
typography_spectrum: 0.08731290721334517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2597841985989362
  lightness: 0.8733551157638431
  saturation: 0.6089471976738423
  rhythmicContrast: 0.293159076012671
purpose: []
